//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FrontendWebService.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BackEndSoap", Namespace="http://tempuri.org/")]
    public partial class BackEnd : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback calculadoraOperationCompleted;
        
        private System.Threading.SendOrPostCallback fatorialOperationCompleted;
        
        private System.Threading.SendOrPostCallback calcularImcOperationCompleted;
        
        private System.Threading.SendOrPostCallback conversaoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BackEnd() {
            this.Url = global::FrontendWebService.Properties.Settings.Default.FrontendWebService_localhost_BackEnd;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event calculadoraCompletedEventHandler calculadoraCompleted;
        
        /// <remarks/>
        public event fatorialCompletedEventHandler fatorialCompleted;
        
        /// <remarks/>
        public event calcularImcCompletedEventHandler calcularImcCompleted;
        
        /// <remarks/>
        public event conversaoCompletedEventHandler conversaoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/calculadora", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float calculadora(float n1, float n2, string operador) {
            object[] results = this.Invoke("calculadora", new object[] {
                        n1,
                        n2,
                        operador});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void calculadoraAsync(float n1, float n2, string operador) {
            this.calculadoraAsync(n1, n2, operador, null);
        }
        
        /// <remarks/>
        public void calculadoraAsync(float n1, float n2, string operador, object userState) {
            if ((this.calculadoraOperationCompleted == null)) {
                this.calculadoraOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalculadoraOperationCompleted);
            }
            this.InvokeAsync("calculadora", new object[] {
                        n1,
                        n2,
                        operador}, this.calculadoraOperationCompleted, userState);
        }
        
        private void OncalculadoraOperationCompleted(object arg) {
            if ((this.calculadoraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculadoraCompleted(this, new calculadoraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fatorial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int fatorial(int x) {
            object[] results = this.Invoke("fatorial", new object[] {
                        x});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void fatorialAsync(int x) {
            this.fatorialAsync(x, null);
        }
        
        /// <remarks/>
        public void fatorialAsync(int x, object userState) {
            if ((this.fatorialOperationCompleted == null)) {
                this.fatorialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfatorialOperationCompleted);
            }
            this.InvokeAsync("fatorial", new object[] {
                        x}, this.fatorialOperationCompleted, userState);
        }
        
        private void OnfatorialOperationCompleted(object arg) {
            if ((this.fatorialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fatorialCompleted(this, new fatorialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/calcularImc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string calcularImc(float peso, float altura) {
            object[] results = this.Invoke("calcularImc", new object[] {
                        peso,
                        altura});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void calcularImcAsync(float peso, float altura) {
            this.calcularImcAsync(peso, altura, null);
        }
        
        /// <remarks/>
        public void calcularImcAsync(float peso, float altura, object userState) {
            if ((this.calcularImcOperationCompleted == null)) {
                this.calcularImcOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalcularImcOperationCompleted);
            }
            this.InvokeAsync("calcularImc", new object[] {
                        peso,
                        altura}, this.calcularImcOperationCompleted, userState);
        }
        
        private void OncalcularImcOperationCompleted(object arg) {
            if ((this.calcularImcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calcularImcCompleted(this, new calcularImcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/conversao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float conversao(float metros, string medida) {
            object[] results = this.Invoke("conversao", new object[] {
                        metros,
                        medida});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void conversaoAsync(float metros, string medida) {
            this.conversaoAsync(metros, medida, null);
        }
        
        /// <remarks/>
        public void conversaoAsync(float metros, string medida, object userState) {
            if ((this.conversaoOperationCompleted == null)) {
                this.conversaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconversaoOperationCompleted);
            }
            this.InvokeAsync("conversao", new object[] {
                        metros,
                        medida}, this.conversaoOperationCompleted, userState);
        }
        
        private void OnconversaoOperationCompleted(object arg) {
            if ((this.conversaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.conversaoCompleted(this, new conversaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void calculadoraCompletedEventHandler(object sender, calculadoraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculadoraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculadoraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void fatorialCompletedEventHandler(object sender, fatorialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fatorialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fatorialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void calcularImcCompletedEventHandler(object sender, calcularImcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calcularImcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calcularImcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void conversaoCompletedEventHandler(object sender, conversaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class conversaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal conversaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591